[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'sha256-aLzVagpeJkVxSzDsocX2cJqjd+04kAvfQaOwgVX329w=' 'sha256-fro5IROozoiD/hOzgKIf+WbbSC/o+ZJBLukWMNV/SP0=' 'sha256-qpWSdXLwOrBSkyLSEzkjaJWk7tmdUROFI6LrF/9tYEU=' 'sha256-foNlzYuzpZ56sN5rvVRfHmouqbFltnLnctWRv0Ws/Ls=' 'sha256-DUeFLNckab6IKbGnFuxoW+jrGdpqU4ddI3fthbWlIxk=' 'sha256-4jFhbH3kM2QdTQDG39om8MF0eRQPyDHCpoJac8qIbJk=' 'sha256-wZIWG5Ymx2F6hB8QNyK9aoqza+KrRIcpHxYbG3oRi2Y=' 'sha256-RD5MBn4Y4a4hrURqhuvsky3mCoIUjtVxEULKyEMx9+w=' 'sha256-iB3dW1bkmZMTxS8h8SVh4724wvNai9QdKUVD0I31vAo=' 'wasm-unsafe-eval' https://www.gstatic.com https://apis.google.com https://www.googletagmanager.com https://checkout.razorpay.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; media-src 'self' blob:; worker-src 'self' blob:; connect-src 'self' https://www.google.com blob: data: https://*.googleapis.com https://www.gstatic.com https://api.web3forms.com https://*.google-analytics.com https://*.analytics.google.com https://www.googletagmanager.com https://api.razorpay.com https://lumberjack.razorpay.com; frame-src https://chaitainya-hptu.firebaseapp.com https://accounts.google.com https://apis.google.com https://api.razorpay.com https://checkout.razorpay.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
